Keywords = ["education",
            "summary",
            "academic",
            "accomplishments",
            "executive profile",
            "professional profile",
            "professional experience",
            "personal profile",
            "work background",
            "academic profile",
            "other activities",
            "qualifications",
            "experience",            
            "academic credentials",
            "interests",
            "skills",
            "achievements",
            "publications",
            "publication",
            "certifications",
            "workshops",
            "projects",
            "personal details",
            "internships",
            "trainings",
            "hobbies",
            "overview",
            "objective",
            "position of responsibility",
            "jobs",
            "work history",                                    
            "work experience",
            "work-experience",
            "certificates",
            "education:",           
            "education details:",
            "e d u c a t i 0 n",
            "employment"
           ]


NAME_PATTERN = [{'POS': 'PROPN'}, {'POS': 'PROPN'}]


 
